#!/usr/bin/env python3
"""Embeds the ray tracing GLSL sources into src/_RayTracerShaders.h

Run this after editing any .glsl/.comp/.vert/.frag file in this directory:
    python3 misc/raytracing/embed_shaders.py
The generated header is committed so that no Python is needed to build the game.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, '..', '..', 'src', '_RayTracerShaders.h')

COMMON = 'rt_common.glsl'
SHADERS = [
	('RT_TRACE_SRC',     'rt_trace.comp',     True),
	('RT_TEMPORAL_SRC',  'rt_temporal.comp',  True),
	('RT_ATROUS_SRC',    'rt_atrous.comp',    True),
	('RT_COMPOSITE_VS',  'rt_composite.vert', False),
	('RT_COMPOSITE_FS',  'rt_composite.frag', True),
]

def read(name):
	with open(os.path.join(HERE, name), 'r') as f:
		return f.read()

def to_c_string(text):
	lines = []
	for line in text.split('\n'):
		line = line.replace('\\', '\\\\').replace('"', '\\"')
		lines.append('\t"%s\\n"' % line)
	return '\n'.join(lines)

def main():
	common = read(COMMON)
	out = []
	out.append('/* AUTO-GENERATED by misc/raytracing/embed_shaders.py - do not edit by hand */')
	out.append('/* Edit the files in misc/raytracing/ and re-run the script instead */')
	out.append('#ifndef CC_RAYTRACER_SHADERS_H')
	out.append('#define CC_RAYTRACER_SHADERS_H')
	out.append('')

	for macro, name, with_common in SHADERS:
		src = '#version 430\n'
		if with_common: src += common + '\n'
		src += read(name)
		out.append('static const char* const %s =' % macro)
		out.append(to_c_string(src) + ';')
		out.append('')

	out.append('#endif')
	# the game's C sources use CRLF line endings
	with open(OUT, 'w', newline='\r\n') as f:
		f.write('\n'.join(out) + '\n')
	print('wrote', os.path.normpath(OUT))

if __name__ == '__main__':
	main()
