#!/usr/bin/env python3
"""Generates example/model.obj and example/model.png: a blocky robot with the same
proportions as ClassiCube's humanoid model, split into the named parts the
BlenderModel plugin animates. Only needs the Python standard library.

Coordinates are in blocks, Y up, facing -Z, exactly what the plugin expects
(and what Blender's OBJ exporter produces with its default axis settings)."""
import struct
import zlib
import os

TEX_W, TEX_H = 48, 40  # deliberately not a power of two: the plugin pads it

# name, (x1, y1, z1), (x2, y2, z2) in 16ths of a block, colour, pivot (blocks) or None
PARTS = [
    ("Head",  (-4, 24, -4), (4, 32, 4), (220, 190, 150), (0, 1.5, 0)),
    ("Body",  (-4, 12, -2), (4, 24, 2), (60, 110, 200),  None),
    ("Arm.L", (-8, 12, -2), (-4, 24, 2), (220, 190, 150), (-0.3125, 1.375, 0)),
    ("Arm.R", (4, 12, -2), (8, 24, 2),   (220, 190, 150), (0.3125, 1.375, 0)),
    ("Leg.L", (-4, 0, -2), (0, 12, 2),   (50, 50, 140),   (-0.125, 0.75, 0)),
    ("Leg.R", (0, 0, -2), (4, 12, 2),    (50, 50, 140),   None),  # no pivot: plugin derives one
]


def write_png(path, width, height, rows):
    raw = b"".join(b"\x00" + bytes(row) for row in rows)

    def chunk(tag, data):
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n")
        f.write(chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)))
        f.write(chunk(b"IDAT", zlib.compress(raw, 9)))
        f.write(chunk(b"IEND", b""))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    pixels = [[(0, 0, 0, 0)] * TEX_W for _ in range(TEX_H)]

    # Give every part its own 8x8 patch of texture, with a darker border so faces are visible
    patches = {}
    for i, (name, _, _, col, _) in enumerate(PARTS):
        px, py = (i % 6) * 8, (i // 6) * 8
        patches[name] = (px, py)
        for y in range(8):
            for x in range(8):
                edge = x in (0, 7) or y in (0, 7)
                r, g, b = col
                shade = 0.6 if edge else 1.0
                pixels[py + y][px + x] = (int(r * shade), int(g * shade), int(b * shade), 255)

    rows = [[c for px in row for c in px] for row in pixels]
    write_png(os.path.join(here, "model.png"), TEX_W, TEX_H, rows)

    lines = ["# ClassiCube BlenderModel example (generated by make_example.py)",
             "# eye 1.625",
             "# size 0.5375 1.75625 0.5375"]
    for name, _, _, _, pivot in PARTS:
        if pivot:
            lines.append("# pivot %s %g %g %g" % ((name,) + pivot))

    v_count = 0
    vt_count = 0
    vn_count = 0
    # Face normals in the order they are emitted below
    normals = [(0, 1, 0), (0, -1, 0), (0, 0, -1), (0, 0, 1), (-1, 0, 0), (1, 0, 0)]
    for nx, ny, nz in normals:
        lines.append("vn %g %g %g" % (nx, ny, nz))
    vn_count = len(normals)

    for name, (x1, y1, z1), (x2, y2, z2), _, _ in PARTS:
        x1, y1, z1, x2, y2, z2 = [c / 16.0 for c in (x1, y1, z1, x2, y2, z2)]
        lines.append("o %s" % name)
        corners = [(x1, y1, z1), (x2, y1, z1), (x2, y2, z1), (x1, y2, z1),
                   (x1, y1, z2), (x2, y1, z2), (x2, y2, z2), (x1, y2, z2)]
        for c in corners:
            lines.append("v %g %g %g" % c)

        px, py = patches[name]
        u1, u2 = (px + 0.5) / TEX_W, (px + 7.5) / TEX_W
        # OBJ V runs bottom-up, so flip the pixel rows
        v1, v2 = 1 - (py + 7.5) / TEX_H, 1 - (py + 0.5) / TEX_H
        for u, v in ((u1, v1), (u2, v1), (u2, v2), (u1, v2)):
            lines.append("vt %g %g" % (u, v))

        # Faces as counter-clockwise quads viewed from outside (local corner indices)
        faces = [
            ([3, 2, 6, 7], 1),  # top    (+Y)
            ([0, 4, 5, 1], 2),  # bottom (-Y)
            ([0, 1, 2, 3], 3),  # front  (-Z)
            ([5, 4, 7, 6], 4),  # back   (+Z)
            ([4, 0, 3, 7], 5),  # left   (-X)
            ([1, 5, 6, 2], 6),  # right  (+X)
        ]
        for idx, n in faces:
            lines.append("f " + " ".join("%d/%d/%d" % (v_count + i + 1, vt_count + k + 1, n)
                                         for k, i in enumerate(idx)))
        v_count += 8
        vt_count += 4

    with open(os.path.join(here, "model.obj"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote model.obj (%d parts) and model.png (%dx%d)" % (len(PARTS), TEX_W, TEX_H))


if __name__ == "__main__":
    main()
